# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa1002088a8ce80d97c1d9c64daec616aa340eaaf1a836e50c4953dd38c95e44e15d1b97564ad4a1e8fc53c1c0e541f87a56a0e2ff9aa8d64a3149fd5f28375

test:
  secret_key_base: ba48599da377589f53ca587e9706150a27f1b2e5afe34434f140ca4e6d9aceb9f5e4698a8598b447bf4f65e45811662725d8cb7b70d736acd9d5ff3029839bfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
